name: newproject
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true